export const demoCampaign = {
  _id: "demo1",
  title: "IQRA Education School",
  slug: "IQRA Education School",
  description:
    "Transparent crowdfunding : daily toppers and real-time donation feed.",
  goalAmount: 5000000,
  raisedAmount: 1875000,
  isActive: true,
  coverImage: "",
};

export const demoLeaderboard = {
  today: [
    { rank: 1, donorName: "Ahamed", total: 25000, count: 1 },
    { rank: 2, donorName: "Farhan", total: 15000, count: 1 },
    { rank: 3, donorName: "Anonymous", total: 10000, count: 1 },
    { rank: 4, donorName: "Nisha", total: 7500, count: 1 },
    { rank: 5, donorName: "Rahul", total: 5000, count: 1 },
  ],
  overall: [
    { rank: 1, donorName: "Shahid", total: 150000, count: 5 },
    { rank: 2, donorName: "Nisha", total: 120000, count: 4 },
    { rank: 3, donorName: "Ahamed", total: 100000, count: 3 },
    { rank: 4, donorName: "Anonymous", total: 90000, count: 6 },
    { rank: 5, donorName: "Farhan", total: 80000, count: 2 },
    { rank: 6, donorName: "Rahul", total: 75000, count: 3 },
  ],
};

export const demoRecentDonations = [
  {
    id: "d1",
    receiptNo: "RCP-0001",
    paymentId: "PAY_DEMO_91A2X",
    status: "PAID",
    donorName: "Anonymous",
    donorPhone: "",
    donorEmail: "",
    address: "",
    note: "Keep going!",
    amount: 10000,
    paidAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "d2",
    receiptNo: "RCP-0002",
    paymentId: "PAY_DEMO_38K9Q",
    status: "PAID",
    donorName: "Nisha",
    donorPhone: "9876543210",
    donorEmail: "nisha@email.com",
    address: "Bengaluru, Karnataka",
    note: "Happy to support this initiative.",
    amount: 7500,
    paidAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
  {
    id: "d3",
    receiptNo: "RCP-0003",
    paymentId: "PAY_DEMO_77T1M",
    status: "PAID",
    donorName: "Farhan",
    donorPhone: "9000011111",
    donorEmail: "farhan@email.com",
    address: "Mysuru, Karnataka",
    note: "All the best!",
    amount: 15000,
    paidAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "d4",
    receiptNo: "RCP-0004",
    paymentId: "",
    status: "PLEDGED",
    donorName: "Rahul",
    donorPhone: "9123456780",
    donorEmail: "rahul@email.com",
    address: "Chennai, Tamil Nadu",
    note: "Will pay tomorrow",
    amount: 5000,
    paidAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
];
